# Тематические карты {#thematic-maps}

## Конфессиональная представленность территории

Карта отражает количество единиц определенных конфессий в тех или иных населенных пунктах и муниципальных районах. 

## Объекты с охранным статусом

Карта показывает местонахождение культовых объектов с охранным статусом и их характеристики.

## Внутриконфессиональные связи

Карта представляет наличие связей между централизованными религиозными организациями и местными религиозными организациями, культовыми объектами, паломническими центрами.

## Численность религиозных общин

Местонахождение общин, маркируемых в зависимости от числа участников их молитвенных собраний.

## Зоны религиозного влияния

Карта показывает населенные пункты, где проводят обряды религиозные специалисты той или иной общины, а также откуда приходят участники обрядов в культовый объект той или иной местности.

## Площадки внутриконфессиональных взаимодействий

Населенные пункты, где находятся площадки взаимодействий религиозных объединений определенных конфессий.

## Площадки межконфессиональных взаимодействий

Населенные пункты, в которых находятся площадки взаимодействий религиозных объединений разных конфессий.

## Паломнические маршруты

Карта паломнических маршрутов различных конфессий.
