# Публикации {#publications}

### Статьи в академических журналах{-}

***

Поплавский Р.О.,  Черепанов М.С., Бобров И.В., Шишелякина А.Л. Протестантский ландшафт Тюменской области: места, численность и демографический состав городских молитвенных собраний // Вестник археологии, антропологии и этнографии. 2022. № 2(57). С. 191-201.

<https://doi.org/10.20874/2071-0437-2022-57-2-15>{target="_blank"}  


<details>
  <summary>Подробнее</summary><i>
Представлены результаты полевого исследования, проведенного в Тюмени, Тобольске, Ишиме и Ялуторовске (Россия, Тюменская область). Показаны численность и демографические особенности протестантских еженедельных молитвенных собраний. Установлено, что наиболее крупная группа прихожан - женщины среднего возраста. Выявлено увеличение количества протестантских объединений в период с 2008 по 2016 г. Больше всего общин и наиболее многочисленные молитвенные собрания находятся в г. Тюмени.</i>
</details>

***

Мусульманские объединения и культовые объекты в Тюменской области. Иллюстрированный справочник / М.С. Черепанов, К.Б. Кабдулвахитов. Тюмень, АНО ИИЦ «Красное знамя». 2021. 164 с.

<https://www.elibrary.ru/download/elibrary_46444714_69527718.pdf>{target="_blank"}

<details>
  <summary>Подробнее</summary><i>
В справочнике представлены сведения об исповедании ислама на территории Тюменской области. Основную его часть составляет информация о местоположении, численности и социально-демографическом составе мусульманских объединений, их культовых объектах, лидерах и выдающихся людях общин, религиозных обрядах и общественной деятельности объединений. Особое место занимают статьи, описывающие историю ислама в Тюменском регионе. Справочник адресован государственным и муниципальным служащим, педагогической общественности, журналистам, членам религиозных организаций и в целом широкому кругу читателей, интересующихся историей и современностью ислама в России.</i>
</details>

***

Бобров И.В., Черепанов М.С., Шишелякина А.Л. Православный ландшафт Тюменской области: места, численность и демографический состав городских молитвенных собраний // Вестник археологии, антропологии и этнографии. № 3. 2019. С. 157-169.

<https://doi.org/10.20874/2071-0437-2019-46-3-157-169>{target="_blank"}

<details>
  <summary>Подробнее</summary><i>
Представлены результаты полевого исследования, проведенного в городах Тюмени, Ишиме и Ялуторовске (Россия, Тюменская область). Показаны особенности и выделены факторы распределения верующих по городским храмам. Установлено, что наиболее крупными демографическими группами коллективных богослужений являются женщины среднего и пожилого возраста. Наблюдается положительная динамика численности участников молитвенных собраний г. Тюмени с 2009 по 2016 г. В качестве причин роста определены открытие новых храмов и увеличение числа горожан.</i>
</details>

***

Бобров И.В., Черепанов М.С. Исламский ландшафт Тюменской области: места, численность и социально-демографический состав городских молитвенных собраний // Исламоведение. № 4. 2019. С. 46-58.

<https://doi.org/10.21779/2077-8155-2019-10-4-46-58>{target="_blank"}

<details>
  <summary>Подробнее</summary><i>
Исследования исламского ландшафта в России, посвященные анализу динамики численности и социально-демографического состава мусульман, включающихся в обязательные коллективные молитвы, нуждаются в доработке. Эта проблема особенно актуальна для регионов, где ислам является религией меньшинства. В данной статье представлены результаты эмпирического исследования социально-демографического состава и динамики численности участников пятничных и праздничных коллективных молитв в трёх городах Тюменской области (Тобольске, Ишиме, Ялуторовске) в 2008–2019 гг. В качестве основного метода исследования использовалось невключённое структурированное наблюдение. Также для сбора и проверки данных использовался метод экспертного интервью с религиозными специалистами. В результате нами зафиксированы изменения исламских ландшафтов трёх городов. В населённых пунктах с положительной динамикой населения или высокими темпами трудовой миграции растёт число мужчин-мусульман, включающихся в догматически обязательные мечетные практики. В Тобольске, где наблюдается большой поток трудовых мигрантов, это происходит главным образом за счёт мужчин молодого и среднего возраста, большую часть из которых составляют выходцы из Северного Кавказа и мигранты из Центральной Азии и Южного Кавказа. В Ялуторовске значительно меньше трудовых мигрантов. Рост прихожан происходит за счёт мужчин молодого и среднего возраста, большую часть из которых составляют местные жители из числа татар. В Ишиме на фоне сокращающейся численности населения, при отсутствии трудовой миграции и несмотря на открытие новых мест для молитв, участников молитвенных собраний становитсянесколько меньше. Большую часть коллективных собраний Ишима составляют мужчины молодого и среднего возраста из числа местных казахов.</i>
</details>

***

Бобров И.В., Черепанов М.С. Исламский ландшафт городского округа Тюмень: места, численность и социально-демографический состав молитвенных собраний // Вестник археологии, антропологии и этнографии. № 4. 2018. С. 193-203.

<https://doi.org/10.20874/2071-0437-2018-43-4-193-203>{target="_blank"}

<details>
  <summary>Подробнее</summary><i>
Представлены результаты анализа эмпирического исследования социально-демографического состава и динамики численности участников пятничных и праздничных коллективных молитв в городском округе Тюмень в 2009–2016 гг. Основным методом исследования являлось невключенное структурированное наблюдение. Полученные данные уточнялись в ходе экспертных интервью с религиозными специалистами и анализа мусульманских средств массовой информации и коммуникации. В результате нами установлена положительная динамика численности участников догматически обязательных молитвенных собраний и зафиксирован их социально-демографический состав. Наиболее крупной группой участников коллективных молитв являются мужчины молодого и среднего возраста, большую часть которых составляют внутренние мигранты с Северного Кавказа и внешние мигранты из Центральной Азии и с Южного Кавказа</i>
</details>

***

Poplavsky R., Klyueva V. From an encounter with God to a life with God: typology of conversion in Russifn Pentecostal churches // PentecoStudies. 2017. Т. 16. № 2. С. 178-201.

<https://doi.org/10.1558/ptcs.33489>{target="_blank"}


<details>
  <summary>Подробнее</summary><i>
This article suggests a typology of conversion to Pentecostalism in Russia, based on research among believers in the Russian Khanty-Mansi Autonomous District, Yugra, West Siberia. The typology of religious conversion is based on the analysis of the motives and causes that led the believers to God. The authors identify four types of conversion: socially induced, induced by a religious crisis, induced by a life crisis, and induced by an existential crisis. The socially induced conversion includes a family sub-type, while a rehabilitation sub-type is identified within the conversion induced by a life crisis. The results obtained demonstrate that the reasons for religious conversion in contemporary Russia are, to some extent, rooted in such social problems as addiction to drugs and alcohol, which people seek to abandon in a church. In addition, the authors give a brief overview of the history of the Pentecostal communities in the region under consideration and of their social and demographic characteristics.</i>
</details>

***

Поплавский Р.О. Тюменские протестантские общины в контексте "религиозного возрождения" 1990–2000-х гг. // Вестник археологии, антропологии и этнографии. 2013. № 1 . С. 118-123.

<https://www.elibrary.ru/download/elibrary_21114352_22547433.pdf>{target="_blank"}

<details>
  <summary>Подробнее</summary><i>
На примере тюменских протестантских церквей рассматривается процесс «религиозного возрождения» в России, анализируется количественный рост общин и их численность в 1990–2000-х гг., а также такие факторы, сдерживающие эти процессы, как церковные расколы, узконаправленная социальная деятельность и др.</i>
</details>

***

Поплавский (Коробкó) Р.О. Церковные расколы в истории протестантских общин г. Тюмени (XX - XXI вв.) // Вестник Кемеровского государственного университета. 2011. № 4. С. 43-47.

<https://www.elibrary.ru/download/elibrary_17304000_47629220.pdf>{target="_blank"}

<details>
  <summary>Подробнее</summary><i>
В статье анализируются церковные расколы в протестантских общинах Тюменской области в разные исторические периоды. Особое внимание уделяется разделениям, произошедшим за последние два десятилетия: выделяются причины расколов; частные особенности, отличающие региональные процессы от общероссийских; анализируется влияние расколов на количественные характеристики протестантского сообщества и межобщинные отношения.</i>
</details>

***
